version: '3'
services:
  pythonapp:
    container_name: devops-rest
    image: "devops-rest:${IMAGE_TAG}"
    build: ./python/
    command: sh -c "sleep 20s; python3 ./rest_app.py"
    ports:
      - "5003:5003"
    depends_on:
      - mysqldocker

  pythondockertest:
    container_name: devops-rest-test
    image: devops-rest-test
    build: ./pythondockertest/  # Use the same build context as pythonapp
    command: sh -c "sleep 30s; pytest ./docker_tests.py "
#    command: sh -c "pytest ./docker_tests.py "
    depends_on:
      - pythonapp

  mysqldocker:
    container_name: mysql-docker
    image: "mysql:8.0.33"
    build: ./mysqldocker/
    restart: always
    volumes:
      - ./data/mysqldocker:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'mydb'
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3307:3306'



